### PR TITLE
attempting to address #1

### LINKED ISSUE #1: be a well-behaved pull-stream
If the sink always reads synchronously, this module should work fine,
however in some situations it will behave in correctly.

https://github.com/davidchase/pull-dom-events/blob/master/index.js#L7

If an event happens more than once before the sink has read again, it will call the callback twice.
(but with a new value)

There are different ways you could address this, depending on what behavior you want with dom events, but the simplest thing would be to unset `callback` before calling it.

```
if(callback) {
  let _cb = callback
  callback = null
  _cb(err, data)
}
```

then you _know_ callback can never be called twice, even if it's called recursively (before itself has returned)

Another question is what do do about events that happen inbetween calls?
one idea would be to let them drop, so you could have a stream of mousemove events,
and whenever you call read you get either the most recent or the next mouse event.
If you just implement the above suggestion, you'll always get the next mouse event.

you could also keep the most recent event, and respond with that if it hasn't been read yet.

for keyboard events you might want to keep the sequence of events?

### PR DESCRIPTION
**Pull request by davidchase**
**edit**
closes #1

### CODE REVIEW

**Comment by dominictarr** [comment]
I'm a bit confused by `partial` it looks like this will call the callback (`next`) many times?
It should call `next` exactly once, then get the next callback from the next `read` call.

A pull-stream also only ever takes one data argument, so I don't think you need partial.
(if you need two args, use an object, or array, etc)

**Comment by davidchase** [comment]
thanks for the feedback, i am using partial as a `bind` since i need to pass both the next fn and event this seemed cleaner than the before setup

> It should call next exactly once, then get the next callback from the next read call.

ahh i did not realize that.. i guess thats the point i missed

**Comment by davidchase** [comment]
@dominictarr i updated the PR to the original setup + your advice about unsetting the callback so it gets called exactly once.

I was wondering however if there is a situation that i can reproduce to see the callback getting called twice as you mentioned

> If an event happens more than once before the sink has read again, it will call the callback twice.

**Comment by dominictarr** [comment]
I think it would have happened if the sink read more slowly than the event was triggered, since you reset the event. also i'm not sure that the remove listener thing will work properly because you have to pass in the same listener function (right?) and you are partial returns a new function each time you call it?

**Comment by davidchase** [comment]
> also i'm not sure that the remove listener thing will work properly because you have to pass in the same listener function (right?)

yes i believe you are correct again.. i have reverted the PR back to the original state and added the concept of unsetting as mentioned in your issue #1 

thank you for working this through with me

**Comment by dominictarr** [comment]
no problem!

**Comment by davidchase** [comment]
i will merge this and add a few more tests

**Pull request merged**
